// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Calculator.proto

package com.github.dtf.rpc.proto;

public final class Calculator {
  private Calculator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static abstract class CalculatorService
      implements com.google.protobuf.Service {
    protected CalculatorService() {}
    
    public interface Interface {
      public abstract void add(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done);
      
      public abstract void minus(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CalculatorService() {
        @java.lang.Override
        public  void add(
            com.google.protobuf.RpcController controller,
            com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
            com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done) {
          impl.add(controller, request, done);
        }
        
        @java.lang.Override
        public  void minus(
            com.google.protobuf.RpcController controller,
            com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
            com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done) {
          impl.minus(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.add(controller, (com.github.dtf.rpc.proto.CalculatorMsg.RequestProto)request);
            case 1:
              return impl.minus(controller, (com.github.dtf.rpc.proto.CalculatorMsg.RequestProto)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.github.dtf.rpc.proto.CalculatorMsg.RequestProto.getDefaultInstance();
            case 1:
              return com.github.dtf.rpc.proto.CalculatorMsg.RequestProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance();
            case 1:
              return com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void add(
        com.google.protobuf.RpcController controller,
        com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
        com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done);
    
    public abstract void minus(
        com.google.protobuf.RpcController controller,
        com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
        com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.github.dtf.rpc.proto.Calculator.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.add(controller, (com.github.dtf.rpc.proto.CalculatorMsg.RequestProto)request,
            com.google.protobuf.RpcUtil.<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto>specializeCallback(
              done));
          return;
        case 1:
          this.minus(controller, (com.github.dtf.rpc.proto.CalculatorMsg.RequestProto)request,
            com.google.protobuf.RpcUtil.<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.github.dtf.rpc.proto.CalculatorMsg.RequestProto.getDefaultInstance();
        case 1:
          return com.github.dtf.rpc.proto.CalculatorMsg.RequestProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance();
        case 1:
          return com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends com.github.dtf.rpc.proto.Calculator.CalculatorService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void add(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.class,
            com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance()));
      }
      
      public  void minus(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request,
          com.google.protobuf.RpcCallback<com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.class,
            com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto add(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException;
      
      public com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto minus(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto add(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance());
      }
      
      
      public com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto minus(
          com.google.protobuf.RpcController controller,
          com.github.dtf.rpc.proto.CalculatorMsg.RequestProto request)
          throws com.google.protobuf.ServiceException {
        return (com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          com.github.dtf.rpc.proto.CalculatorMsg.ResponseProto.getDefaultInstance());
      }
      
    }
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Calculator.proto\032\023CalculatorMsg.proto2" +
      "a\n\021CalculatorService\022$\n\003add\022\r.RequestPro" +
      "to\032\016.ResponseProto\022&\n\005minus\022\r.RequestPro" +
      "to\032\016.ResponseProtoB/\n\033com.github.dtf.rpc" +
      ".protocolB\nCalculator\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.dtf.rpc.proto.CalculatorMsg.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
